package com.ej.hgj.entity.login;

public class PropOperInfoDo {
	
    private String custId;

    private String poSeqId;
	
    private String poName;
    
    private String deptName;

    private String stat;

    private String poWxId;

    private String poMp;

    private String isInfoPub;

    private String hgjOpenId;

    private String openDate;
    
    private Integer rateScore;
    
    private Integer rateCnt;

    public String getPoName() {
        return poName;
    }

    public String getCustId() {
		return custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public String getPoSeqId() {
		return poSeqId;
	}

	public void setPoSeqId(String poSeqId) {
		this.poSeqId = poSeqId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prop_oper_info.PO_NAME
     *
     * @param poName the value for prop_oper_info.PO_NAME
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public void setPoName(String poName) {
        this.poName = poName;
    }

    public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prop_oper_info.STAT
     *
     * @return the value of prop_oper_info.STAT
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prop_oper_info.STAT
     *
     * @param stat the value for prop_oper_info.STAT
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public void setStat(String stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prop_oper_info.PO_WX_ID
     *
     * @return the value of prop_oper_info.PO_WX_ID
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public String getPoWxId() {
        return poWxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prop_oper_info.PO_WX_ID
     *
     * @param poWxId the value for prop_oper_info.PO_WX_ID
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public void setPoWxId(String poWxId) {
        this.poWxId = poWxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prop_oper_info.PO_MP
     *
     * @return the value of prop_oper_info.PO_MP
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public String getPoMp() {
        return poMp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prop_oper_info.PO_MP
     *
     * @param poMp the value for prop_oper_info.PO_MP
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public void setPoMp(String poMp) {
        this.poMp = poMp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prop_oper_info.IS_INFO_PUB
     *
     * @return the value of prop_oper_info.IS_INFO_PUB
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public String getIsInfoPub() {
        return isInfoPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prop_oper_info.IS_INFO_PUB
     *
     * @param isInfoPub the value for prop_oper_info.IS_INFO_PUB
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public void setIsInfoPub(String isInfoPub) {
        this.isInfoPub = isInfoPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prop_oper_info.HGJ_OPEN_ID
     *
     * @return the value of prop_oper_info.HGJ_OPEN_ID
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public String getHgjOpenId() {
        return hgjOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prop_oper_info.HGJ_OPEN_ID
     *
     * @param hgjOpenId the value for prop_oper_info.HGJ_OPEN_ID
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public void setHgjOpenId(String hgjOpenId) {
        this.hgjOpenId = hgjOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prop_oper_info.OPEN_DATE
     *
     * @return the value of prop_oper_info.OPEN_DATE
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prop_oper_info.OPEN_DATE
     *
     * @param openDate the value for prop_oper_info.OPEN_DATE
     *
     * @mbg.generated Thu Aug 06 14:26:09 CST 2020
     */
    public void setOpenDate(String openDate) {
        this.openDate = openDate;
    }

	public Integer getRateScore() {
		return rateScore;
	}

	public void setRateScore(Integer rateScore) {
		this.rateScore = rateScore;
	}

	public Integer getRateCnt() {
		return rateCnt;
	}

	public void setRateCnt(Integer rateCnt) {
		this.rateCnt = rateCnt;
	}

}